---

- hosts: all
  become: true
  pre_tasks:

  - name: Install update (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Update repository index (CentOS)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: ubuntu_server
  become: true
  roles:
    - ubuntu_server

- hosts: centos_server
  become: true
  roles:
    - centos_server
